# MOVIE

### Get all movies

GET http://localhost:12345/api/movies/
userId: 67964782c8b5942c5f45547f

### Create a new movie

POST http://localhost:12345/api/movies/
userId: 67964782c8b5942c5f45547f
Content-Type: application/json

{
"name": "SpiderMan 3", 
"categories":[], 
"movie_time":"2:30", 
"image":"", 
"Publication_year":2012, 
"description": "good one", 
"age": 10
}

### Return movie according to user search

GET http://localhost:12345/api/movies/search/:query
userId: <ID>

### Get a specific movie by ID

GET http://localhost:12345/api/movies/:id 
userId: <ID>

### Update a movie

PUT http://localhost:12345/api/movies/6797f5b69a55cc86adcf5455
Content-Type: application/json 
userId: 67964782c8b5942c5f45547f

{
"name": "after change", 
"categories":[], 
"movie_time":"2:30", 
"image":"", 
"Publication_year":2024, 
"description": "try.", 
"age":18
}

### Delete a movie

DELETE http://localhost:12345/api/movies/6784155156b0b833f090f588 
userId: <ID>

### Get recommendation

GET http://localhost:12345/api/movies/:id/recommend/ 
userId: <ID>

### Add movie to user's watchlist

POST http://localhost:12345/api/movies/6784155156b0b833f090f588/recommend/ 
Content-Type: application/json 
userId: <ID>

# CATEGORY

### Get all categories

GET http://localhost:12345/api/categories/ 
userId: 67964782c8b5942c5f45547f

### Create a new category

POST http://localhost:12345/api/categories/ 
userId: <ID> 
Content-Type: application/json

{
"name": "Family", "isPromoted": false, "movies": []
}

### Get a specific category by ID

GET http://localhost:12345/api/categories/67956f7405674a481f9f6fde 
userId: 6793f41b8221f4dda02b7e63

### Update a category

PATCH http://localhost:12345/api/categories/6784159856b0b833f090f58d 
userId: <ID> 
Content-Type: application/json

{ 
  "name": "Action & Adventure", 
  "isPromoted": false, 
  "movies": [] 
}

### Delete a category

DELETE http://localhost:12345/api/categories/67841e6efb9dec98b33abb5e 
userId: <ID>

#USER

### Create a new user

POST http://localhost:12345/api/users/ 
Content-Type: application/json

{
"username": "lioriii", 
"password": "123456", 
"nickname": "liori",
"isAdmin": true
}

### Connect to system

POST http://localhost:12345/api/tokens/ 
Content-Type: application/json

{
"username": "maayan", 
"password": "123456"
}

### Get a specific user by ID

GET http://localhost:12345/api/users/:id 
userId: <ID>


### Upload a video

POST http://localhost:12345/api/upload/video

### Upload an image

POST http://localhost:12345/api/upload/image 

