# MOVIE

### Get all movies

GET http://localhost:12345/api/movies/
userId: 679213ef1cebc10d8c2d7bc3

### Create a new movie

POST http://localhost:12345/api/movies/
userId: 6793d58f1ef6aabb4a5638e1
Content-Type: application/json

{
"name": "SpiderMan 3", 
"categories":[], 
"movie_time":"2:30", 
"image":"", 
"Publication_year":2012, 
"description": "good one", 
"age": 10
}

### Return movie according to user search

GET http://localhost:12345/api/movies/search/:query
userId: <ID>

### Get a specific movie by ID

GET http://localhost:12345/api/movies/6794d57dc3b3353fd3a318ac
userId: 6793d58f1ef6aabb4a5638e1

### Get all movie

GET http://localhost:12345/api/movies/allmovies
userId: 679178e884e6da9a833f5452

### Update a movie

PUT http://localhost:12345/api/movies/:id
Content-Type: application/json 
userId: 6793d58f1ef6aabb4a5638e1

{
"name": "after change", 
"categories":[], 
"movie_time":"2:30", 
"image":"", 
"Publication_year":2024, 
"description": "try.", 
"age":18
}

### Delete a movie

DELETE http://localhost:12345/api/movies/:id 
userId: <ID>

### Get recommendation
GET http://localhost:12345/api/movies/:id/recommend/ 
userId: <ID>

### Add movie to user's watchlist

POST http://localhost:12345/api/movies/:id/recommend/ 
Content-Type: application/json 
userId: 679213ef1cebc10d8c2d7bc3

# CATEGORY

### Get all categories

GET http://localhost:12345/api/categories/ 
userId: 679178e884e6da9a833f5452

### Create a new category

POST http://localhost:12345/api/categories/ 
userId: 6792b52c10a40e0b80dd798d
Content-Type: application/json

{
"name": "Drama", "isPromoted": true, "movies": []
}

### Get a specific category by ID

GET http://localhost:12345/api/categories/:id 
userId: <ID>

### Update a category

PATCH http://localhost:12345/api/categories/:id 
userId: <ID> 
Content-Type: application/json

{ 
  "name": "Action & Adventure", 
  "isPromoted": false, 
  "movies": [] 
}

### Delete a category   

DELETE http://localhost:12345/api/categories/:id 
userId: <ID>

#USER

### Create a new user

POST http://localhost:12345/api/users/ 
Content-Type: application/json

{
"username": "lioriii", 
"password": "123456", 
"nickname": "liori",
"isAdmin": true
}

### Connect to system

POST http://localhost:12345/api/tokens/ 
Content-Type: application/json

{
"username": "maayan", 
"password": "123456"
}

### Get a specific user by ID

GET http://localhost:12345/api/users/:id 
userId: <ID>


### Upload a video

POST http://localhost:12345/api/upload/video

### Upload an image

POST http://localhost:12345/api/upload/image 

