# Get all categories
# GET http://127.0.0.1:12345/categories/

# Create a new category
POST http://127.0.0.1:12345/categories/
Content-Type: application/json

{
  "name": "romance",
  "promoted": "true",
  "movies": ["6772bcb91359e983cd06d677"]
}

# # Get a specific category by ID
# GET http://127.0.0.1:12345/categories/67729fad1ca1dbdd20105c3f

# # Update a category
# PATCH http://127.0.0.1:12345/categories/67729fad1ca1dbdd20105c3f
# Content-Type: application/json

# {
#     "name": "Action & Adventure",
#     "promoted": "true",
#     "movies": [2, 4, 6, 8]
# }

# Delete a category
# DELETE http://127.0.0.1:12345/categories/67729fad1ca1dbdd20105c3f
