# Use the Node.js image
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Copy the project files
COPY package*.json ./
COPY . .

# Install dependencies
RUN npm install

# Expose the port where the API is running (assumed to be 12345)
EXPOSE 12345

# Run the server
CMD ["npm", "start"]
